### ISSUE TITLE
Consider releasing new minor version

### ISSUE THREAD

**Issue by apatrushev** [Pylons/translationstring#33]
PyPI page still refer to wrong docs location. It looks weird a little bit.
This was fixed already in trunk, but not released.

**Comment by stevepiercy** [comment]
Thanks for the report. I found a few other outdated links, and cleaned them up as well.

The two maintainers are @mcdonc and @wichert, and are the only ones I know who can cut a release.

**Comment by wichert** [comment]
I can take a look at that this week. I noticed @jinty added commit 5bfc3acd64966d60fcdc04e78a3fa9fc7506f1e5, that should probably be cleaned up as well.

@stevepiercy did you want to make any other changes? I noticed you just added another issue as well.

**Comment by stevepiercy** [comment]
Thanks, @wichert. We need a definition for the term "translation context" added to `glossary.rst` in #35. I'm not sure what it means, otherwise I would write it up.

**Comment by stevepiercy** [comment]
ping @wichert. I just found an old reference to Chameleon in the last release/dist of translation string. http://chameleon.repoze.org should be https://chameleon.readthedocs.io/en/latest/index.html I made that update a while ago. A new release would be nice.

**Comment by wichert** [comment]
@stevepiercy I'll add it to me list for this week. I'll try to set things up so pushing a tag automatically creates a release.

**Comment by wichert** [comment]
@mcdonc @mmerickel Can either of you grant me permissions to manage the settings for that repo? I need that to enable automatic releases from CI.

**Comment by stevepiercy** [comment]
@wichert I just bumped you up from Write to Maintain in GitHub for this repo. Does that grant you sufficient access?

**Comment by wichert** [comment]
@stevepiercy Looks like it doesn't :(

**Comment by stevepiercy** [comment]
@wichert bumped to Admin. Please try again.

**Comment by stevepiercy** [comment]
https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization yup, that should give you access to "Change a repository's settings".

**Comment by wichert** [comment]
That seems to work! I'm testing the automated release now.

**Comment by wichert** [comment]
@stevepiercy All good now! Pushing a tag now automatically runs the tests and uploads a release to pypi.
